export const projects = [
  {
    num: "01",
    name: "Sculptura",
    desc: "Marketing site for a foam tool insert manufacturer.",
    longDesc:
      "Built for Foam-D Sculptura, a precision foam tool insert manufacturer based in India. Full marketing site with product showcase, Sanity-powered content management, and Framer Motion animations throughout. Designed and developed end-to-end.",
    tag: "Website",
    year: "2025",
    url: "https://dsculptura.in/",
    screenshot: "/projects/sculptura.png",
    stack: ["Next.js", "Framer Motion", "Sanity CMS", "Tailwind"],
    role: "Design + Development",
    live: true,
  },
  {
    num: "02",
    name: "Project Two",
    desc: "Something built from scratch: what problem it solves, who uses it.",
    longDesc: null,
    tag: "Mobile",
    year: "2024",
    url: null,
    screenshot: null,
    stack: [],
    role: null,
    live: false,
  },
  {
    num: "03",
    name: "Project Three",
    desc: "Another build: the context, the stack, the outcome.",
    longDesc: null,
    tag: "Tool",
    year: "2023",
    url: null,
    screenshot: null,
    stack: [],
    role: null,
    live: false,
  },
];
