export type ProjectLayout = "wide" | "phone";

export const projects = [
  {
    num: "01",
    name: "Sculptura",
    desc: "Marketing site for a foam tool insert manufacturer.",
    longDesc:
      "Built for Foam-D Sculptura, a precision foam tool insert manufacturer based in India. Full marketing site with product showcase, Sanity-powered content management, and Framer Motion animations throughout. Designed and developed end-to-end.",
    tag: "Website",
    year: "2025",
    url: "https://dsculptura.in/",
    screenshot: "/projects/sculptura.png",
    layout: "wide" as ProjectLayout,
    stack: ["Next.js", "Framer Motion", "Sanity CMS", "Tailwind"],
    role: "Design + Development",
    live: true,
    statusNote: null as string | null,
  },
  {
    num: "02",
    name: "Atlas",
    desc: "Offline mobile app for tracking strength training, cardio, and body composition.",
    longDesc:
      "Personal workout tracker built for daily gym use. Logs sets with auto rest timer, detects PRs via Epley 1RM, tracks body measurements alongside health metrics (WHtR, WHR, BMI), and ships a round timer for boxing and BJJ. Fully offline, zero cloud, zero cost.",
    tag: "Mobile",
    year: "2026",
    url: null,
    screenshot: "/projects/atlas.jpg",
    layout: "phone" as ProjectLayout,
    stack: ["React Native", "Expo", "SQLite", "TypeScript"],
    role: "Design + Development",
    live: true,
    statusNote: "Not on store",
  },
  {
    num: "03",
    name: "Portfolio",
    desc: "Personal portfolio with dual positioning modes (elevation vs section), editorial and technical drawing aesthetic. Every diagram drawn as inline SVG.",
    longDesc:
      "Career site for Bijin Abraham built as a technical drawing. Holds two positioning modes behind a nav toggle: Elevation (outside view, manager scope and pipeline) and Section (inside view, IC craft and streaming architecture). Every diagram, from the hero portrait to project architectures, is inline SVG in the site's own visual language.",
    tag: "Website",
    year: "2026",
    url: "https://bijinabraham.github.io",
    screenshot: "/projects/portfolio.png",
    layout: "wide" as ProjectLayout,
    stack: ["Next.js 16", "React 19", "Framer Motion", "TypeScript"],
    role: "Design + Development",
    live: true,
    statusNote: null as string | null,
  },
  {
    num: "04",
    name: "Psychology Traits",
    desc: "Autonomous YouTube Shorts pipeline. Two educational Shorts per week on cognitive biases. Runs on GitHub Actions. Zero infra cost.",
    longDesc: null,
    tag: "Automation",
    year: "2026",
    url: null,
    screenshot: null,
    layout: "wide" as ProjectLayout,
    stack: ["Remotion", "ElevenLabs", "Pexels API", "YouTube API", "GitHub Actions", "TypeScript"],
    role: "Design + Development",
    live: false,
    statusNote: "Pipeline built, awaiting channel launch",
  },
];
