export type ProjectLayout = "wide" | "phone";

export const projects = [
  {
    num: "01",
    name: "Sculptura",
    desc: "Marketing site for a foam tool insert manufacturer.",
    longDesc:
      "Built for Foam-D Sculptura, a precision foam tool insert manufacturer based in India. Full marketing site with product showcase, Sanity-powered content management, and Framer Motion animations throughout. Designed and developed end-to-end.",
    tag: "Website",
    year: "2025",
    url: "https://dsculptura.in/",
    screenshot: "/projects/sculptura.png",
    layout: "wide" as ProjectLayout,
    stack: ["Next.js", "Framer Motion", "Sanity CMS", "Tailwind"],
    role: "Design + Development",
    live: true,
    statusNote: null as string | null,
  },
  {
    num: "02",
    name: "Atlas",
    desc: "Offline mobile app for tracking strength training, cardio, and body composition.",
    longDesc:
      "Personal workout tracker built for daily gym use. Logs sets with auto rest timer, detects PRs via Epley 1RM, tracks body measurements alongside health metrics (WHtR, WHR, BMI), and ships a round timer for boxing and BJJ. Fully offline, zero cloud, zero cost.",
    tag: "Mobile",
    year: "2026",
    url: null,
    screenshot: "/projects/atlas.jpg",
    layout: "phone" as ProjectLayout,
    stack: ["React Native", "Expo", "SQLite", "TypeScript"],
    role: "Design + Development",
    live: true,
    statusNote: "Not on store",
  },
  {
    num: "03",
    name: "Project Three",
    desc: "Another build: the context, the stack, the outcome.",
    longDesc: null,
    tag: "Tool",
    year: "2023",
    url: null,
    screenshot: null,
    layout: "wide" as ProjectLayout,
    stack: [],
    role: null,
    live: false,
    statusNote: null as string | null,
  },
];
